# Buổi 03: Phân tích dữ liệu với Python

In [8]:
# !rm -r pydata-book
# !git clone https://github.com/wesm/pydata-book
!ls pydata-book
# !sudo rm -r pydata-book/.git

ls: cannot access 'pydata-book': No such file or directory


In [1]:
# !git status
# !git add . -n
# !git add .
# !git commit -m "buoi03"
# !git push
# !git status
# !git push --force # ép phải commit (nếu xảy ra xung đột)
# !git reset HEAD~  # phục hồi lại trạng thái commit gần nhất

# !git add .
# !git commit -m "buoi03"
# !git push

In [2]:
# !ls
# !mv pydata-book/ ../
# !git add . -n
# !git add .
# !git commit -m "buoi03"
# !git push

In [3]:
v = list(range(1, 6))
print(v)
print(2 * v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [4]:
import numpy as np
v = np.arange(1, 6)
print(v)
print(2 * v)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [5]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [6]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90


In [7]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[ 4 10 18]


In [8]:
import numpy as np

# Tạo mảng toàn số 0
a = np.zeros((5, 5))
print("Mảng toàn số 0:\n", a)

# Tạo mảng toàn số 1
b = np.ones((1, 2))
print("Mảng toàn số 1:\n", b)

# Tạo mảng với giá trị cố định là 7
c = np.full((2, 2), 7)
print("Mảng toàn số 7:\n", c)

# Tạo ma trận đơn vị 2x2
d = np.eye(2)
print("Ma trận đơn vị:\n", d)

# Tạo mảng với giá trị ngẫu nhiên từ 0 đến 1
e = np.random.random((2, 2))
print("Mảng ngẫu nhiên:\n", e)

Mảng toàn số 0:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Mảng toàn số 1:
 [[1. 1.]]
Mảng toàn số 7:
 [[7 7]
 [7 7]]
Ma trận đơn vị:
 [[1. 0.]
 [0. 1.]]
Mảng ngẫu nhiên:
 [[0.9484356  0.53297638]
 [0.23760208 0.46903077]]


In [9]:
import numpy as np
a = np.arange(15)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

a = a.reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
1
int64
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64


In [10]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [11]:
b = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
b = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23],
])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
(3, 4)
int64


In [13]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:2,1:], a[:2,1:].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]] (2, 2)


# Pandas

In [14]:
import pandas as pd
from IPython.display import display

df = pd.DataFrame({
        "a": [4, 5, 6],
        "b": [7, 8, 9],
        "c": [10, 11, 12]
    },
        index = [1, 2, 3])

display(df)
display(df['a'])
display(df.loc[2])

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

1    4
2    5
3    6
Name: a, dtype: int64

a     5
b     8
c    11
Name: 2, dtype: int64

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('pandas imported')

pandas imported


In [17]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [18]:
dates = pd.date_range('20181001', periods=6)
dates

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [19]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [20]:
df_a = pd.DataFrame(
    {'A': pd.Series([1,3,5,np.nan,6,8])}, 
    dtype=float)
df_a

A
0  1.0
1  3.0
2  5.0
3  NaN
4  6.0
5  8.0

In [21]:
df = pd.DataFrame(
    np.random.randn(6,4), 
    index=dates, 
    columns=list('ABCD'))
df

A         B         C         D
2018-10-01 -1.631484 -1.213006  0.143691  1.587410
2018-10-02  0.985641 -0.390338  0.374140 -1.135491
2018-10-03  0.848701  0.019755  0.483045 -1.657264
2018-10-04 -1.114750  0.909903  0.427183 -0.201841
2018-10-05 -1.209927 -2.545900  0.089006  0.014053
2018-10-06 -1.483852 -0.792452  0.396220  0.700547

In [22]:
df = pd.DataFrame(
    np.random.randn(3,5), 
    index=['student1','student2','student3'], 
    columns=list('ABCDE'))
df

A         B         C         D         E
student1  1.160380  0.207375 -0.589580  1.498386 -1.462910
student2  0.663449 -2.137387  0.411841  0.437257  1.501086
student3 -0.722294 -0.011215  0.288839  1.903426  0.034213

In [23]:
df2 = pd.DataFrame(
    { 
        'A' : 1.,
        'B' : pd.Timestamp('20181001'),
        'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
        'D' : np.array([3] * 4,dtype='int32'),
        'E' : pd.Categorical(["test","train","test","train"]),
        'F' : 'foo' })
df2

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [24]:
df3 = pd.DataFrame(
    [
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'test', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'train', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'test', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'train', 'F': 'foo'}
    ]
)
df3

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

# Kết thúc